#Contains API Secret used to validate your application. Commit to internal source control; avoid making secret public.
#Fri Aug 17 09:19:35 WAT 2018
apiSecret=e13490598dbc74c605caf62cf1fc673e430a8aaa42ba5da30d91eec228fb2fb2
